name: Xcode - Build and Analyze

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches: 
      - main
      - feature/*
      - swift-migration
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  test:
    name: Test iOS
    runs-on: macOS-12
    env:
      DEVELOPER_DIR: "/Applications/Xcode_14.1.app/Contents/Developer"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: "Run tests"
        run: xcodebuild -project "attentive-ios-sdk.xcodeproj" -scheme "attentive-ios-sdk-framework" -destination "platform=iOS Simulator,OS=16.1,name=iPhone 13 Pro" test

  lint:
    name: Run Swiftlint
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Set Xcode 15
        run: |
          sudo xcode-select -switch /Applications/Xcode_15.3.app
      - name: Lint
        run: swiftlint
