name: CI

on:
  push:
    branches:
      - test
    paths:
      - "Sources/**"
      - "Tests/**"
  pull_request:
    branches: 
      - test
    paths:
      - "Sources/**"
      - "Tests/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  iOS:
    name: Test iOS
    runs-on: macOS-12
    env:
      DEVELOPER_DIR: "/Applications/Xcode_14.1.app/Contents/Developer"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: "Test"
        run: xcodebuild -project "attentive-ios-sdk.xcodeproj" -scheme "attentive-ios-sdk Tests" -destination "platform=iOS" clean test
