name: Run Unit Test

on:
  push:
    branches:
      - main
      - "feature/*"
      - "release/*"
  pull_request:
    branches: 
      - main
      - "feature/*"
      - "release/*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test iOS
    runs-on: macOS-14
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: "Run tests"
        run: xcodebuild -project "attentive-ios-sdk.xcodeproj" -scheme "attentive-ios-sdk-framework" -destination "platform=iOS Simulator,OS=17.4,name=iPhone 15 Pro" test
