name: Lint

on:
  pull_request:
    branches:
      - develop
      - swift-migration
      - main
      - feature/*

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run Swiftlint
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Set Xcode 15
        run: |
          sudo xcode-select -switch /Applications/Xcode_15.3.app
      - name: Lint
        run: swiftlint